package br.com.alinesolutions.anotaai.metadata.model.domain;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.JsonNodeType;

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum Icone {

	GLYPHICON_ASTERISK("Asterisk", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PLUS("Plus", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EURO("Euro", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EUR("Eur", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MINUS("Minus", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CLOUD("Cloud", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ENVELOPE("Envelope", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PENCIL("Pencil", CategoriaIcone.GLYPHCONS),
	GLYPHICON_GLASS("Glass", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MUSIC("Music", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SEARCH("Search", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HEART("Heart", CategoriaIcone.GLYPHCONS),
	GLYPHICON_STAR("Star", CategoriaIcone.GLYPHCONS),
	GLYPHICON_STAR_EMPTY("Star Empty", CategoriaIcone.GLYPHCONS),
	GLYPHICON_USER("User", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FILM("Film", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TH_LARGE("TH Large", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TH("Th", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TH_LIST("TH List", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OK("Ok", CategoriaIcone.GLYPHCONS),
	GLYPHICON_REMOVE("Remove", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ZOOM_IN("In", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ZOOM_OUT("Out", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OFF("Off", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SIGNAL("Signal", CategoriaIcone.GLYPHCONS),
	GLYPHICON_COG("Cog", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TRASH("Trash", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HOME("Home", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FILE("Film", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TIME("Time", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ROAD("Toad", CategoriaIcone.GLYPHCONS),
	GLYPHICON_DOWNLOAD_ALT("Download Alt", CategoriaIcone.GLYPHCONS),
	GLYPHICON_DOWNLOAD("Download", CategoriaIcone.GLYPHCONS),
	GLYPHICON_UPLOAD("Upload", CategoriaIcone.GLYPHCONS),
	GLYPHICON_INBOX("Inbox", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PLAY_CIRCLE("Circle", CategoriaIcone.GLYPHCONS),
	GLYPHICON_REPEAT("Repeat", CategoriaIcone.GLYPHCONS),
	GLYPHICON_REFRESH("Refresh", CategoriaIcone.GLYPHCONS),
	GLYPHICON_LIST_ALT("List Alt", CategoriaIcone.GLYPHCONS),
	GLYPHICON_LOCK("Lock", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FLAG("Flag", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HEADPHONES("Headphones", CategoriaIcone.GLYPHCONS),
	GLYPHICON_VOLUME_OFF("Volume Off", CategoriaIcone.GLYPHCONS),
	GLYPHICON_VOLUME_DOWN("Volume Dow", CategoriaIcone.GLYPHCONS),
	GLYPHICON_VOLUME_UP("Volume UP", CategoriaIcone.GLYPHCONS),
	GLYPHICON_QRCODE("QRCode", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BARCODE("Barcode", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TAG("Tag", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TAGS("Tags", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BOOK("Book", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BOOKMARK("Bookmark", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PRINT("Print", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CAMERA("Camera", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FONT("Font", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ITALIC("Italic", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TEXT_HEIGHT("Text Height", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TEXT_WIDTH("Text Eidth", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ALIGN_LEFT("Align Left", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ALIGN_CENTER("Align Center", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ALIGN_RIGHT("Align Right", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ALIGN_JUSTIFY("Align Justify", CategoriaIcone.GLYPHCONS),
	GLYPHICON_LIST("List", CategoriaIcone.GLYPHCONS),
	GLYPHICON_INDENT_LEFT("Indent Left", CategoriaIcone.GLYPHCONS),
	GLYPHICON_INDENT_RIGHT("Indent Right", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FACETIME_VIDEO("Facetime Video", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PICTURE("Picture", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MAP_MARKER("Map Marker", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ADJUST("Adjust", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TINT("Tint", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EDIT("Edit", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SHARE("Share", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CHECK("Check", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MOVE("Move", CategoriaIcone.GLYPHCONS),
	GLYPHICON_STEP_BACKWARD("Step Backward", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FAST_BACKWARD("Fast Backward", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BACKWARD("Backward", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PLAY("Play", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PAUSE("Pause", CategoriaIcone.GLYPHCONS),
	GLYPHICON_STOP("Stop", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FORWARD("Forward", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FAST_FORWARD("Fast Forward", CategoriaIcone.GLYPHCONS),
	GLYPHICON_STEP_FORWARD("Step Forward", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EJECT("Eject", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CHEVRON_LEFT("Chevron Left", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CHEVRON_RIGHT("Chevron Right Sign Sign", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PLUS_SIGN("Plus Sign", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MINUS_SIGN("Minus Sign", CategoriaIcone.GLYPHCONS),
	GLYPHICON_REMOVE_SIGN("Remove Sign", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OK_SIGN("Ok Sign", CategoriaIcone.GLYPHCONS),
	GLYPHICON_QUESTION_SIGN("Question Sign", CategoriaIcone.GLYPHCONS),
	GLYPHICON_INFO_SIGN("Info Sign", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SCREENSHOT("Screenshot", CategoriaIcone.GLYPHCONS),
	GLYPHICON_REMOVE_CIRCLE("Remove Circle", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OK_CIRCLE("Ok Circle", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BAN_CIRCLE("Ban Circle", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ARROW_LEFT("Arrow Left", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ARROW_RIGHT("Arrow Right", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ARROW_UP("Arrow Up", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ARROW_DOWN("Arrow Down", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SHARE_ALT("Share Alt", CategoriaIcone.GLYPHCONS),
	GLYPHICON_RESIZE_FULL("Resize Full", CategoriaIcone.GLYPHCONS),
	GLYPHICON_RESIZE_SMALL("Resize Small", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EXCLAMATION_SIGN("Exclamation Sign", CategoriaIcone.GLYPHCONS),
	GLYPHICON_GIFT("Gift", CategoriaIcone.GLYPHCONS),
	GLYPHICON_LEAF("Leaf", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FIRE("Fire", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EYE_OPEN("Eye Open", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EYE_CLOSE("Eye Close", CategoriaIcone.GLYPHCONS),
	GLYPHICON_WARNING_SIGN("Warning Sign", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PLANE("Plane", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CALENDAR("Calendar", CategoriaIcone.GLYPHCONS),
	GLYPHICON_RANDOM("Random", CategoriaIcone.GLYPHCONS),
	GLYPHICON_COMMENT("Comment", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MAGNET("Magnet", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CHEVRON_UP("Up", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CHEVRON_DOWN("Down", CategoriaIcone.GLYPHCONS),
	GLYPHICON_RETWEET("Retweet", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SHOPPING_CART("Shopping Cart", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FOLDER_CLOSE("Folder Close", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FOLDER_OPEN("Folder Open", CategoriaIcone.GLYPHCONS),
	GLYPHICON_RESIZE_VERTICAL("Resize Vertical", CategoriaIcone.GLYPHCONS),
	GLYPHICON_RESIZE_HORIZONTAL("Resize Horizontal", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HDD("HDD", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BULLHORN("Bullhorn", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BELL("Bell", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CERTIFICATE("Certificate", CategoriaIcone.GLYPHCONS),
	GLYPHICON_THUMBS_UP("Thumbs Up", CategoriaIcone.GLYPHCONS),
	GLYPHICON_THUMBS_DOWN("Thumbs Down", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HAND_RIGHT("Hand Right", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HAND_LEFT("Hand Left", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HAND_UP("Hand Up", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HAND_DOWN("Hand Down", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CIRCLE_ARROW_RIGHT("Circle Arrow Right", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CIRCLE_ARROW_LEFT("Circle Arrow Left", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CIRCLE_ARROW_UP("Circle Arrow Up", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CIRCLE_ARROW_DOWN("Circle Arrow Down", CategoriaIcone.GLYPHCONS),
	GLYPHICON_GLOBE("Globe", CategoriaIcone.GLYPHCONS),
	GLYPHICON_WRENCH("Wrench", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TASKS("Tasks", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FILTER("Filter", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BRIEFCASE("Briefcase", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FULLSCREEN("Fullscreen", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PAPERCLIP("Paperclip", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HEART_EMPTY("Heart Empty", CategoriaIcone.GLYPHCONS),
	GLYPHICON_LINK("Link", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PHONE("Phone", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PUSHPIN("", CategoriaIcone.GLYPHCONS),
	GLYPHICON_USD("USD", CategoriaIcone.GLYPHCONS),
	GLYPHICON_GBP("GBP", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SORT("SORT", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SORT_BY_ALPHABET("Sort By Alphabet", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SORT_BY_ALPHABET_ALT("Sort By Alphabet Alt", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SORT_BY_ORDER_ALT("Sort By Order Alt", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SORT_BY_ATTRIBUTES("Sort By Attibutes", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SORT_BY_ATTRIBUTES_ALT("Sort By Attributes Alt", CategoriaIcone.GLYPHCONS),
	GLYPHICON_UNCHECKED("Unchecked", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EXPAND("Expand", CategoriaIcone.GLYPHCONS),
	GLYPHICON_COLLAPSE_DOWN("Collapse Down", CategoriaIcone.GLYPHCONS),
	GLYPHICON_COLLAPSE_UP("Collapse Up", CategoriaIcone.GLYPHCONS),
	GLYPHICON_LOG_IN("Log In", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FLASH("Flash", CategoriaIcone.GLYPHCONS),
	GLYPHICON_LOG_OUT("Log Out", CategoriaIcone.GLYPHCONS),
	GLYPHICON_NEW_WINDOW("New Window", CategoriaIcone.GLYPHCONS),
	GLYPHICON_RECORD("Record", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SAVE("Save", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OPEN("Open", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SAVED("Saved", CategoriaIcone.GLYPHCONS),
	GLYPHICON_IMPORT("Import", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EXPORT("Export", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SEND("Send", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FLOPPY_DISK("Floppy Disk", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FLOPPY_SAVED("Floppy Saved", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FLOPPY_REMOVE("Floppy Remove", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FLOPPY_SAVE("Floppy Save", CategoriaIcone.GLYPHCONS),
	GLYPHICON_FLOPPY_OPEN("Floppu Oppen", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CREDIT_CARD("Credit Card", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TRANSFER("Transfer", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CUTLERY("Cutlery", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HEADER("Header", CategoriaIcone.GLYPHCONS),
	GLYPHICON_COMPRESSED("Compressed", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EARPHONE("Earphone", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PHONE_ALT("Phone Alt", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TOWER("Tower", CategoriaIcone.GLYPHCONS),
	GLYPHICON_STATS("Stats", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SD_VIDEO("SD Video", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HD_VIDEO("HD Video", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SUBTITLES("Subtitles", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SOUND_STEREO("Sound Stereo", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SOUND_DOLBY("Sound Dolby", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SOUND_5_1("Sound 5 1", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SOUND_6_1("Sound 6 1", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SOUND_7_1("Sound 7 1", CategoriaIcone.GLYPHCONS),
	GLYPHICON_COPYRIGHT_MARK("Copyrigh Mark", CategoriaIcone.GLYPHCONS),
	GLYPHICON_REGISTRATION_MARK("Registration Mark", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CLOUD_DOWNLOAD("Cloud Download", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CLOUD_UPLOAD("Cloud Upload", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TREE_CONIFER("Tree Conifer", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TREE_DECIDUOUS("Tree Deciduous", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CD("CD", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SAVE_FILE("Save File", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OPEN_FILE("Open File", CategoriaIcone.GLYPHCONS),
	GLYPHICON_LEVEL_UP("Level Up", CategoriaIcone.GLYPHCONS),
	GLYPHICON_COPY("Copy", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PASTE("Paste", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ALERT("Alert", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EQUALIZER("Equalizer", CategoriaIcone.GLYPHCONS),
	GLYPHICON_KING("King", CategoriaIcone.GLYPHCONS),
	GLYPHICON_QUEEN("Queen", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PAWN("Pawn", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BISHOP("Bishop", CategoriaIcone.GLYPHCONS),
	GLYPHICON_KNIGHT("Knight", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BABY_FORMULA("Baby Formula", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TENT("Tent", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BLACKBOARD("Blackboard", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BED("Bed", CategoriaIcone.GLYPHCONS),
	GLYPHICON_APPLE("Apple", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ERASE("Erase", CategoriaIcone.GLYPHCONS),
	GLYPHICON_HOURGLASS("Hourglass", CategoriaIcone.GLYPHCONS),
	GLYPHICON_LAMP("", CategoriaIcone.GLYPHCONS),
	GLYPHICON_DUPLICATE("Duplicate", CategoriaIcone.GLYPHCONS),
	GLYPHICON_PIGGY_BANK("Piggy Bank", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SCISSORS("Scissors", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BITCOIN("Bitcoin", CategoriaIcone.GLYPHCONS),
	GLYPHICON_BTC("Btc", CategoriaIcone.GLYPHCONS),
	GLYPHICON_XBT("XBT", CategoriaIcone.GLYPHCONS),
	GLYPHICON_YEN("Yen", CategoriaIcone.GLYPHCONS),
	GLYPHICON_JPY("Jpy", CategoriaIcone.GLYPHCONS),
	GLYPHICON_RUBLE("Rule", CategoriaIcone.GLYPHCONS),
	GLYPHICON_RUB("Rub", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SCALE("Scale", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ICE_LOLLY("Ice Lolly", CategoriaIcone.GLYPHCONS),
	GLYPHICON_ICE_LOLLY_TASTED("Ice Lollu Tasted", CategoriaIcone.GLYPHCONS),
	GLYPHICON_EDUCATION("Education", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OPTION_HORIZONTAL("Option Horizontal", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OPTION_VERTICAL("Option Vertical", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MENU_HAMBURGER("Menu Hamburger", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MODAL_WINDOW("Modal Window", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OIL("Oil", CategoriaIcone.GLYPHCONS),
	GLYPHICON_GRAIN("Grain", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SUNGLASSES("Sunglasses", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TEXT_SIZE("Text Size", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TEXT_COLOR("Text Collor", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TEXT_BACKGROUND("Text Background", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OBJECT_ALIGN_TOP("Object Align Top", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OBJECT_ALIGN_BOTTOM("Object Align Botton", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OBJECT_ALIGN_HORIZONTAL("Object Align Horizontal", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OBJECT_ALIGN_LEFT("Object Align Left", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OBJECT_ALIGN_VERTICAL("Object Vertical", CategoriaIcone.GLYPHCONS),
	GLYPHICON_OBJECT_ALIGN_RIGHT("Object Align Right", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TRIANGLE_RIGHT("Triangle Right", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TRIANGLE_LEFT("Triangle Left", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TRIANGLE_BOTTOM("Triangle Botton", CategoriaIcone.GLYPHCONS),
	GLYPHICON_TRIANGLE_TOP("Triangle Top", CategoriaIcone.GLYPHCONS),
	GLYPHICON_CONSOLE("Console", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SUPERSCRIPT("Supersript", CategoriaIcone.GLYPHCONS),
	GLYPHICON_SUBSCRIPT("Subscript", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MENU_LEFT("Menu Feft", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MENU_RIGHT("Menu Right", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MENU_DOWN("Menu Down", CategoriaIcone.GLYPHCONS),
	GLYPHICON_MENU_UP("Menu Up", CategoriaIcone.GLYPHCONS);
	
	private Icone(String descricao, CategoriaIcone categoria) {
		this.descricao = descricao;
		this.categoria = categoria;
		this.nameClass = this.toString().toLowerCase().replace("_", "-");
	}
	
	private String nameClass;
	
	private CategoriaIcone categoria;
	
	private String descricao;
	
	public String getDescricao() {
		return descricao;
	}
	
	public CategoriaIcone getCategoriaIcone() {
		return categoria;
	}

	public String getNameClass() {
		return nameClass;
	}
	
	// TODO - Adicionar metodos dinamicamente
	public String getType() {
		return this.toString();
	}

	public String getPropertieKey() {
		StringBuilder sb = new StringBuilder("enum.");
		sb.append(this.getClass().getName()).append(".");
		sb.append(toString());
		return sb.toString().toLowerCase();
	}

	@JsonCreator
	public static Icone fromObject(JsonNode node) {
		String type = null;
		if (node.getNodeType().equals(JsonNodeType.STRING)) {
			type = node.asText();
		} else {
			if (!node.has("type")) {
				throw new IllegalArgumentException();
			}
			type = node.get("type").asText();
		}
		return valueOf(type);
	}
	
}
